server {
    listen 80 default_server;
    server_name _;
    root /var/www/html/public;
    index index.php;

    client_max_body_size 16M;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/javascript application/xml application/xml+rss text/xml image/svg+xml;
    gzip_min_length 256;

    add_header X-Real-Client-IP $remote_addr;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_pass web:9000;
        fastcgi_index index.php;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_read_timeout 60s;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
